version: "3.3"

services:

    mysql_5_7:
        build:
          context: ./docker/mysql_5_7
          args:
            - MYSQL_VERSION=${MYSQL_VERSION_5_7}
        container_name: ${MYSQL_CONTAINER_NAME_5_7}
        environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_DATABASE=${MYSQL_ROOT_PASSWORD}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
          - "${MYSQL_PORT_5_7}:3306"        
        volumes:
          - ${MYSQLDATA_PATH_HOST_5_7}:/var/lib/mysql
          - ${MYSQL_ENTRYPOINT_INITDB_5_7}:/docker-entrypoint-initdb.d
          - /etc/localtime:/etc/localtime:ro 
        restart: always

    mysql_5_6:
        build:
          context: ./docker/mysql_5_6
          args:
            - MYSQL_VERSION=${MYSQL_VERSION_5_6}
        container_name: ${MYSQL_CONTAINER_NAME_5_6}
        environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_DATABASE=${MYSQL_ROOT_PASSWORD}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
          - "${MYSQL_PORT_5_6}:3306"        
        volumes:
          - ${MYSQLDATA_PATH_HOST_5_6}:/var/lib/mysql
          - ${MYSQL_ENTRYPOINT_INITDB_5_6}:/docker-entrypoint-initdb.d
          - /etc/localtime:/etc/localtime:ro 
        restart: always
    mongodb:
        privileged: true
        build:                  
          context: ./docker/mongodb
          args:
            - MONGODB_VERSION=${MONGODB_VERSION}          
        sysctls:
            - net.core.somaxconn=4096
            - net.ipv4.tcp_fin_timeout=30
            - net.ipv4.tcp_keepalive_intvl=30
            - net.ipv4.tcp_keepalive_time=120
            - net.ipv4.tcp_max_syn_backlog=4096            
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "10m"                  
        container_name: ${MONGODB_CONTAINER_NAME}
        restart: always
        volumes:
            - ${MONGODB_PATH_HOST}/${MONGODB_VERSION}:/data/db
            - /etc/localtime:/etc/localtime:ro  
            - /docker/mongodb/mongodb-sysctl.conf:/etc/sysctl.d/mongodb-sysctl.conf         
            - ${MONGODB_PATH_DUMPS_HOST}:/backup 
        environment:          
          MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
          MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ports:
            - "${MONGODB_PORT}:27017"        
networks:
  default:
    external:
      name: ${NETWORK}